import type {
  WAMessage,
} from "@whiskeysockets/baileys";

// ============================================================
// 🌑 DARK VORTEX — OUTGOING MESSAGE TRACKER
// ⚡ Powered by Vortex Tech
// ============================================================
//
// Purpose:
//
// Distinguish messages generated by Dark Vortex from messages
// manually sent by the owner from the same WhatsApp account.
//
// This is primarily used by the Owner Availability / Away
// system.
//
// ============================================================

const trackedMessageIds =
  new Map<string, number>();

const MESSAGE_EXPIRY_MS =
  2 * 60 * 60 * 1000;


// ============================================================
// TRACK BOT MESSAGE
// ============================================================

export function trackOutgoingMessage(
  message: WAMessage | undefined,
): void {

  const id =
    message?.key?.id;

  if (!id) {
    return;
  }

  trackedMessageIds.set(
    id,
    Date.now(),
  );
}


// ============================================================
// CHECK WHETHER MESSAGE WAS GENERATED BY BOT
// ============================================================

export function isTrackedOutgoingMessage(
  messageId: string | undefined,
): boolean {

  if (!messageId) {
    return false;
  }

  cleanupTrackedMessages();

  return trackedMessageIds.has(
    messageId,
  );
}


// ============================================================
// REMOVE MESSAGE
// ============================================================

export function untrackOutgoingMessage(
  messageId: string | undefined,
): void {

  if (!messageId) {
    return;
  }

  trackedMessageIds.delete(
    messageId,
  );
}


// ============================================================
// CLEAN EXPIRED MESSAGE IDS
// ============================================================

function cleanupTrackedMessages(): void {

  const now =
    Date.now();

  for (
    const [
      id,
      timestamp,
    ] of trackedMessageIds
  ) {

    if (
      now -
        timestamp >
      MESSAGE_EXPIRY_MS
    ) {
      trackedMessageIds.delete(
        id,
      );
    }
  }
}


// ============================================================
// PERIODIC CLEANUP
// ============================================================

setInterval(
  cleanupTrackedMessages,
  30 * 60 * 1000,
);